#!/usr/bin/env python3
"""Utility for sending SMTP email with optional HTTP proxy support."""
from __future__ import annotations

import argparse
import ssl
import sys
from email.message import EmailMessage

try:
    import smtplib
except ImportError as exc:  # pragma: no cover
    raise SystemExit(f"Failed to import smtplib: {exc}")


def configure_proxy(proxy: str) -> None:
    """Configure an HTTP proxy for outgoing SMTP connections."""
    try:
        import socks
        import socket
    except ImportError as exc:  # pragma: no cover
        raise SystemExit(
            "PySocks is required for proxy support. Install it via 'pip install PySocks'."
        ) from exc

    host, port_str = proxy.split(":", 1)
    try:
        port = int(port_str)
    except ValueError as exc:  # pragma: no cover
        raise SystemExit(f"Invalid proxy port {port_str!r}: {exc}") from exc

    socks.setdefaultproxy(socks.HTTP, host, port)
    socket.socket = socks.socksocket  # type: ignore[assignment]


def build_message(sender: str, recipient: str, subject: str, body: str) -> EmailMessage:
    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(body)
    return message


def send_email(
    sender: str,
    password: str,
    recipient: str,
    subject: str,
    body: str,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 465,
    proxy: str | None = None,
) -> None:
    if proxy:
        configure_proxy(proxy)

    message = build_message(sender, recipient, subject, body)
    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context, timeout=30) as smtp:
        smtp.login(sender, password)
        smtp.send_message(message)



def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sender", required=True, help="Email address to authenticate as")
    parser.add_argument("--password", required=True, help="Password for the sender account")
    parser.add_argument("--recipient", required=True, help="Recipient email address")
    parser.add_argument("--subject", default="Test email", help="Email subject")
    parser.add_argument(
        "--body",
        default="This is a test email generated by send_email.py",
        help="Email body text",
    )
    parser.add_argument(
        "--smtp-host",
        default="smtp.gmail.com",
        help="SMTP server hostname",
    )
    parser.add_argument(
        "--smtp-port",
        type=int,
        default=465,
        help="SMTP server port",
    )
    parser.add_argument(
        "--proxy",
        help="Optional HTTP proxy in host:port format for outgoing connections",
    )
    return parser.parse_args(argv)



def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    try:
        send_email(
            sender=args.sender,
            password=args.password,
            recipient=args.recipient,
            subject=args.subject,
            body=args.body,
            smtp_host=args.smtp_host,
            smtp_port=args.smtp_port,
            proxy=args.proxy,
        )
    except Exception as exc:  # pragma: no cover
        print(f"Failed to send email: {exc}", file=sys.stderr)
        return 1

    print("Email sent successfully")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
